config/routes.rb
Rails.application.routes.draw do

  root 'oracle#index'

  get 'first_exercise' => 'first_exercise#index', as: :first_ex
    get 'simple_table' => 'simple_table#simple_menu', as: :simple_table
    post 'simple_table' => 'simple_table#simple_table', as: :simple_table_for
    get 'double_table' => 'double_table#double_menu', as: :double_table
    post 'double_table' => 'double_table#function_selector', as: :selector_table

  get 'index' => 'index#table_selection', as: :index_table
  post 'index' => 'index#create', as: :index_for

  get 'validation' => 'validation#validation', as: :validation

  get 'create_find' => 'find_wrapper#show', as: :find_wrapper
  post 'submit_find' => 'find_wrapper#submit', as: :find_wrapper_submit

  get 'benchmark' => 'benchmark#index', as: :benchmark
  post 'insert_into' => 'benchmark#insert_into', as: :insert_into
  post 'select_from' => 'benchmark#select_from', as: :select_from

  get  'attrs_for_table' => 'oracle#get_attrs', as: :oracle_attrs

end

app/controllers/find_wrapper_controller.rb
class FindWrapperController < ApplicationController
  # get
  def show
    # list all tables
    i = 0
    @options = []
    # fill the options array with all tables
    Oracle.each_row('user_tables') do |row|
      @options[i] = [row['TABLE_NAME'], row['TABLE_NAME']]
      i = i + 1
    end
    # fill the options array with all views
    Oracle.each_row('user_views') do |row|
      @options[i] = [row['VIEW_NAME'], row['VIEW_NAME']]
      i = i + 1
    end


    # list all operators
    @operators = %w($eq $gt $gte $lt $lte $ne $in $nin $not $exists $type)
  end

  # post
  def submit
    find_string = []
    query = []
    @table_name = params['table'].upcase
    mux = params[:mux] == '0' ? 'and' : 'or'

    args = params.select do |k, _v|
      /table_(attr|operator|operand)_\d+/ =~ k
    end

    (0..args.length/3 - 1).each do |i|
      attr = args["table_attr_#{i}"]
      operator = args["table_operator_#{i}"]
      operand = args["table_operand_#{i}"]
      type = Oracle.get_types(@table_name, attr)[0]


      if operator == '$exists'
        if ['FALSE', '0', ''].include? operand.upcase
          operand = false
        else
          operand = true
        end
        hash = {attr.to_sym=> {operator => operand}}
        find_string.append(hash)

      elsif operator == '$in' || operator == '$nin'
        operand = operand.split(',').map {|el| el.strip}
        if /CHAR/i =~ type
          hash = {attr.to_sym=> {operator.to_sym => operand}}
          find_string.append(hash)
        elsif type == 'NUMBER'
          new_operand = operand.map do |item| item.to_i end
          hash = {attr.to_sym=> {operator.to_sym => new_operand}}
          find_string.append(hash)
        end
      elsif /CHAR/i =~ type
        hash = { attr.to_sym => { operator.to_sym => operand } }
        find_string.append(hash)
      elsif type == 'NUMBER'
        hash = { attr.to_sym => { operator.to_sym => operand.to_i } }
        find_string.append(hash)
      end
    end
    puts 'find_string: '
    puts find_string

    @query_hash = if find_string.length == 1
                    find_string[0]
                  else
                    { "$#{mux}" => find_string }
                  end

    puts @query_hash
    collection = MongoModel.collection @table_name
    cursor = collection.find(@query_hash)
    puts cursor.inspect
    cursor.each do |k|
      tuple = k
      puts tuple
      query.append(tuple)
    end
    @query = query
    puts 'result'
    puts query.inspect
  end
end

app/helpers/find_wrapper_helper.rb
module FindWrapperHelper
end

app/views/find_wrapper/_partial_show.html.erb
<div class="row" id = 'partial_'>
  <div class="col-md-4">
    <%= f.select(:table_attr_, options_for_select([]), { label: 'Selecione um atributo:' }, { class: 'attrs_selector' }) %>
  </div>
  <div class="col-md-4">
    <%= f.select(:table_operator_, options_for_select(@operators), { label: 'Selecione um operador' }, { class: 'attrs_operator'}) %>
  </div>
  <div class="col-md-4">
    <%= f.text_field(:table_operand_, label: 'Digite o operando', class: 'attrs_operand') %>
  </div>
</div>

app/views/find_wrapper/show.html.erb
<script type="text/javascript" charset="utf-8">
  var attr_selector;
  $(document).ready(function () {
    getAttrs();
    $('#table_selector').change(getAttrs);
    function getAttrs() {
      $('#add_partial').attr('data-counter', '0');
      $('#partial_anchor').empty();
      $.ajax({
        url: "<%= oracle_attrs_path %>",
        type: "GET",
        dataType: "json",
        data: {table: $('#table_selector').find('option:selected').text(), no_pk: true},
        complete: function () {
        },
        success: function (data, test_staus, xhr) {
          var attrs = data.response;
          var options = '';
          for (var i = 0; i < attrs.length; i++) {
            options += '<option value="' + attrs[i] + '">' + attrs[i] + '</option>';
          }
          attr_selector = options;
          var attrs_selector = $('.attrs_selector');
          attrs_selector.empty();
          attrs_selector.append(attr_selector);
        }
      })
    }

    $('#add_partial').click(function () {
      var partial = $('#batata').html();
      var i = $(this).attr('data-counter');
      var new_partial = partial.replace(new RegExp('table_attr_', 'g'), 'table_attr_'+i);
      new_partial = new_partial.replace(new RegExp('table_operator_', 'g'), 'table_operator_'+i);
      new_partial = new_partial.replace(new RegExp('table_operand_', 'g'), 'table_operand_'+i);

      $(this).attr('data-counter', parseInt(i, 10) + 1);
      $('#partial_anchor').append(new_partial);

    });
  })
</script>

<%= bootstrap_form_tag url: find_wrapper_submit_path, method: :post do |f| %>
    <%= f.select(:table, options_for_select(@options), { label: 'Selecione a tabela para busca:' }, { id: 'table_selector' }) %>
    <div id="partial_anchor"></div>
    <%= link_to 'Adicionar campo de busca','#', id: 'add_partial',class: 'btn btn-md btn-primary', data: {counter: 0 }%>
    <%= f.submit :buscar, class: 'btn btn-md btn-success' %>
    <%= f.form_group :mux do %>
        <%= f.label :mux_0 do %>
            AND
            <%= radio_button_tag :mux, 0, text: 'usar $and', checked: true %>
        <% end %>
        <%= label_tag :mux_1 do %>
            OR
            <%= radio_button_tag :mux, 1, text: 'usar $or' %>
        <% end %>
    <% end %>
    <div class="hide" id="batata">
    <%= render(partial: 'partial_show', locals: {f: f}) %>
    </div>
<% end %>

app/views/find_wrapper/submit.html.erb
<pre id="result">
  <p>Query gerada</p>
db.<%=@table_name%>.find(<%= @query_hash.to_json %>);
  <p>Resultado</p>
<% @query.each_with_index do |item, i| %>
resultado #<%=i%>: <%= item.to_s.gsub(/=>/, ' : ') %>
  <% end %>
</pre>