config/routes.rb
Rails.application.routes.draw do

  root 'oracle#index'

  get 'first_exercise' => 'first_exercise#index', as: :first_ex
    get 'simple_table' => 'simple_table#simple_menu', as: :simple_table
    post 'simple_table' => 'simple_table#simple_table', as: :simple_table_for
    get 'double_table' => 'double_table#double_menu', as: :double_table
    post 'double_table' => 'double_table#function_selector', as: :selector_table

  get 'index' => 'index#table_selection', as: :index_table
  post 'index' => 'index#create', as: :index_for

  get 'validation' => 'validation#validation', as: :validation

  get 'create_find' => 'find_wrapper#show', as: :find_wrapper
  post 'submit_find' => 'find_wrapper#submit', as: :find_wrapper_submit

  get 'benchmark' => 'benchmark#index', as: :benchmark
  post 'insert_into' => 'benchmark#insert_into', as: :insert_into
  post 'select_from' => 'benchmark#select_from', as: :select_from

  get  'attrs_for_table' => 'oracle#get_attrs', as: :oracle_attrs

end

app/controllers/double_table_controller.rb
class DoubleTableController < ApplicationController
  # GET /double_table
  def double_menu
    @options_table = []
    i = 0
    # fill the options array with all tables
    Oracle.each_row('user_tables') do |row|
      @options_table[i] = [row['TABLE_NAME'], row['TABLE_NAME']]
      i = i + 1
    end
    # fill the options array with all views
    Oracle.each_row('user_views') do |row|
      @options_table[i] = [row['VIEW_NAME'], row['VIEW_NAME']]
      i = i + 1
    end

  end

  # POST /double_table
  def function_selector

    embedding = params[:embed] == '1'

    table1 = params[:table1].upcase
    attr1 = params[:attr1].upcase
    table2 = params[:table2].upcase
    attr2 = params[:attr2].upcase

    tup_arr_t1 = MongoModel.represent_table(table1)
    tup_arr_t2 = MongoModel.represent_table(table2, !embedding)

    tup_arr_t1.each do |tup|

      look_for = tup[attr1].nil? ? tup['_id'][attr1] : tup[attr1]

      i = tup_arr_t2.find_index do |item|
        puts "looking for '#{look_for}' in '#{item.inspect}'"
        item[attr2] == look_for || (!item['_id'].nil? && item['_id'][attr2] == look_for )
      end

      unless i.nil?
        to_set = tup_arr_t2[i]
        to_set = to_set['_id'] unless embedding

        if tup[attr1].nil?
          # tup['_id'][attr1] = to_set
          tup['_id'][table2] = to_set
          tup['_id'].delete attr1
        else
          # tup[attr1] = to_set
          tup[table2] = to_set
          tup.delete attr1
        end
      end
    end

    if params[:run]
      MongoModel.drop table1
      MongoModel.insert_many table1, tup_arr_t1
    end

    @oracle = {table_name: table1, tuples: tup_arr_t1, back_path: double_table_path}

    render 'oracle/mongo_script'
  end
end

app/views/double_table/double_menu.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    $('#table_one_selector').change(function () {
      getAttrs($(this), '#attr_one_selector');
    });
    $('#table_two_selector').change(function () {
      getAttrs($(this), '#attr_two_selector');
    });
    function getAttrs(t, attr_id) {
      $.ajax({
        url: "<%= oracle_attrs_path %>",
        type: "GET",
        dataType: "json",
        data: {table: t.find('option:selected').text()},
        complete: function () {
        },
        success: function (data, test_staus, xhr) {
          var attrs = data.response;
          var options = '';
          for (var i = 0; i < attrs.length; i++) {
            options += '<option value="' + attrs[i] + '">' + attrs[i] + '</option>';
          }
          var attr_selector = $(attr_id);
          attr_selector.empty();
          attr_selector.append(options);
        }
      })
    }
  })
</script>
<%= bootstrap_form_tag url: selector_table_path, method: :post do |f| %>


    <%= f.select(:table1, options_for_select(@options_table), {label: 'Selecione a tabela principal' }, {id: 'table_one_selector' }) %>
    <%= f.select(:attr1, options_for_select([]), { label: 'Selecione o atributo a ser unido' }, { id: 'attr_one_selector' }) %>

    <%= f.select(:table2, options_for_select(@options_table), {label: 'Selecione a tabela estrangeira' }, {id: 'table_two_selector' }) %>
    <%= f.select(:attr2, options_for_select([]), { label: 'Selecione o atributo referenciado' }, { id: 'attr_two_selector' }) %>

    <%= f.form_group :embed do %>
        <%= f.label :embed_0 do %>
            Usar Referencia
            <%= radio_button_tag :embed, 0, checked: true %>
        <% end %>
        <%= label_tag :embed_1 do %>
            Usar 'Embedding'
        <%= radio_button_tag :embed, 1 %>
        <% end %>
    <% end %>

    <%= f.form_group do %>
      <%= check_box_tag(:run) %>
      <%= f.label 'Criar coleção no MongoDB' %>
    <% end %>

    <%= f.primary 'Gerar script MongoDB' %>



<% end %>