config/routes.rb
Rails.application.routes.draw do

  root 'oracle#index'

  get 'first_exercise' => 'first_exercise#index', as: :first_ex
    get 'simple_table' => 'simple_table#simple_menu', as: :simple_table
    post 'simple_table' => 'simple_table#simple_table', as: :simple_table_for
    get 'double_table' => 'double_table#double_menu', as: :double_table
    post 'double_table' => 'double_table#function_selector', as: :selector_table

  get 'index' => 'index#table_selection', as: :index_table
  post 'index' => 'index#create', as: :index_for

  get 'validation' => 'validation#validation', as: :validation

  get 'create_find' => 'find_wrapper#show', as: :find_wrapper
  post 'submit_find' => 'find_wrapper#submit', as: :find_wrapper_submit

  get 'benchmark' => 'benchmark#index', as: :benchmark
  post 'insert_into' => 'benchmark#insert_into', as: :insert_into
  post 'select_from' => 'benchmark#select_from', as: :select_from

  get  'attrs_for_table' => 'oracle#get_attrs', as: :oracle_attrs

end

app/controllers/benchmark_controller.rb
class BenchmarkController < ApplicationController
  def index
  end

  # POST
  def insert_into
    n = params[:number].to_i

    inserts = (0..n).map do |i|
      {
        _id: i,
        name1: random_string(2000), name2: random_string(2000),
        name3: random_string(2000), name4: random_string(2000),
        name5: random_string(2000), name6: random_string(2000),
        name7: random_string(2000), name8: random_string(2000),
        name9: random_string(2000), name10: random_string(2000)
      }
    end

    puts 'starting benchmark with index'
    time = MongoModel.benchmark_insert(inserts, false)

    puts 'starting benchmark without index'
    time_index = MongoModel.benchmark_insert(inserts, true)

    redirect_to root_url, notice: "O MongoDB levou #{time}s (sem index) e #{time_index}s (com index) para inserir #{n} tuplas"

    # render json: {time: time, number: n}
  end

  def select_from
    n = params[:number].to_i
    r = params[:rand].to_i
    nums = []
    names = []

    collection = MongoModel.collection('insert_test')
    (0..100).each { nums.append rand(r) }
    nums.each do |i|
      collection.find(_id: { :$eq => i }).each { |j| names.append j['name1'] }
    end

    puts 'starting benchmark without index'
    time = Benchmark.realtime do
      (0..n).each do |i|
        collection.find(name1: { :$eq => names[i % names.length] })
      end
    end

    names = []
    collection = MongoModel.collection('insert_test_index')
    (0..100).each { nums.append rand(r) }
    nums.each do |i|
      collection.find(_id: { :$eq => i }).each { |j| names.append j['name1'] }
    end

    puts 'starting benchmark with index'
    time_index = Benchmark.realtime do
      (0..n).each do |i|
        collection.find(name1: { :$eq => names[i % names.length] })
      end
    end

    msg = "O MongoDB levou #{time}s (sem index) e #{time_index}s (com index) para inserir #{n} tuplas"
    redirect_to root_url, notice: msg
  end

  private

  def random_string(length)
    (36**(length - 1) + rand(36**length)).to_s(36)
  end
end

app/helpers/benchmark_helper.rb
module BenchmarkHelper
  def random_string(length)
    (36**(length-1) + rand(36**length)).to_s(36)
  end

  def insert_into(document_name, n)

  end
end

app/views/benchmark/index.html.erb
<script type="text/javascript" charset="utf-8">

  $(document).ready(function () {
    $("#insert_into").click(function () {
      $("#loader")[0].style.display = 'block';
      $.ajax({
        url: <%= insert_into_path %>,
        type: 'POST',
        dataType: 'json',
        data: {number: $('#number').val()},
        complete: function () { },
        success: function (data, test_status, xhr) {
          $("#loader")[0].style.display = 'none';
          window.append(data.number);

        }
      })
    });
  });

</script>
<style>
  /* Center the loader */
  #loader {
    /*position: absolute;*/
    /*left: 50%;*/
    /*top: 50%;*/
    /*z-index: 1;*/
    width: 15px;
    height: 15px;
    margin: -75px 0 0 -75px;
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 12px;
    height: 12px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
  }

  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  /* Add animation to "page content" */
  .animate-bottom {
    position: relative;
    -webkit-animation-name: animatebottom;
    -webkit-animation-duration: 1s;
    animation-name: animatebottom;
    animation-duration: 1s
  }

  @-webkit-keyframes animatebottom {
    from { bottom:-100px; opacity:0 }
    to { bottom:0px; opacity:1 }
  }

  @keyframes animatebottom {
    from{ bottom:-100px; opacity:0 }
    to{ bottom:0; opacity:1 }
  }

  #myDiv {
    display: none;
    text-align: center;
  }
</style>

<h2>Realizar Inserções</h2>
<%= bootstrap_form_tag url: insert_into_path, method: :post do |f| %>
    <%= f.text_field :number, label: 'Número de vezes' %>
    <%# link_to 'insert into', '#', id: 'insert_into', class: 'btn btn-md btn-primary' %>
    <%= f.submit 'Realizar inserções' %>
<% end %>

<h2>Realizar Buscas</h2>
<%= bootstrap_form_tag url: select_from_path, method: :post do |f| %>
    <%= f.text_field :number, label: 'Número de vezes' %>
    <%= f.text_field :rand, label: 'Max random' %>
    <%= f.submit 'Realizar Buscas' %>
<% end %>

<div id="loader" style="display: none"></div>