config/routes.rb
Rails.application.routes.draw do

  root 'oracle#index'

  get 'first_exercise' => 'first_exercise#index', as: :first_ex
    get 'simple_table' => 'simple_table#simple_menu', as: :simple_table
    post 'simple_table' => 'simple_table#simple_table', as: :simple_table_for
    get 'double_table' => 'double_table#double_menu', as: :double_table
    post 'double_table' => 'double_table#function_selector', as: :selector_table

  get 'index' => 'index#table_selection', as: :index_table
  post 'index' => 'index#create', as: :index_for

  get 'validation' => 'validation#validation', as: :validation

  get 'create_find' => 'find_wrapper#show', as: :find_wrapper
  post 'submit_find' => 'find_wrapper#submit', as: :find_wrapper_submit

  get 'benchmark' => 'benchmark#index', as: :benchmark
  post 'insert_into' => 'benchmark#insert_into', as: :insert_into
  post 'select_from' => 'benchmark#select_from', as: :select_from

  get  'attrs_for_table' => 'oracle#get_attrs', as: :oracle_attrs

end

app/models/oracle.rb
class Oracle
  def self.execute(sql)
    ActiveRecord::Base.connection.execute(sql)
  end

  def self.transaction(sql)
    result_set = Oracle.execute(sql)
    yield result_set
    result_set.close
  end

  def self.each_row(table)
    sql = "select * from #{table}"
    Oracle.each_row_sql(sql) do |entry|
      yield entry
    end
  end

  def self.each_row_sql(sql)
    Oracle.transaction(sql) do |result_set|
      result_set.fetch_hash do |entry|
        yield entry
      end
    end
  end

  def self.get_constraint(table, type)
    sql = "SELECT column_name FROM all_cons_columns WHERE constraint_name = (
            SELECT constraint_name FROM user_constraints
            WHERE UPPER(table_name) = UPPER('#{table}') AND CONSTRAINT_TYPE = '#{type}')"
    constraints = []
    Oracle.each_row_sql(sql) do |entry|
      constraints.append entry['COLUMN_NAME'].upcase
    end

    constraints
  end

  def self.get_pks(table)
    self.get_constraint table, 'P'
  end

  def self.get_uniques(table)
    self.get_constraint table, 'U'
  end

  def self.get_types(table, attr)
    sql = "SELECT DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '#{table}' AND COLUMN_NAME = '#{attr}'"
    type = []
    Oracle.each_row_sql(sql) do |entry|
      type.append entry['DATA_TYPE'].upcase
    end
    type
  end
end

app/controllers/oracle_controller.rb
class OracleController < ApplicationController
  def dump_script
  end

  def get_attrs
    table = params[:table].upcase # normalize table name to upper case
    pks = []
    no_pk = false
    no_pk ||= params[:no_pk]
    sql = "SELECT * FROM #{table}"
    attrs = []
    Oracle.transaction(sql) do |result|
      result.column_metadata.each do |info|
        attrs.append info.name
      end
    end
    if no_pk
      pks = Oracle.get_pks(table)
    end

   render json:{ :response => attrs-pks }
  end

  def index
  end
end

app/helpers/oracle_helper.rb
module OracleHelper
end

app/views/oracle/_partial_mongo_document.html.erb
use dblabbd_fred_roberto;

db.createCollection("<%= @oracle[:table_name] %>");
<% @oracle[:tuples].each do |tuple| %>
  db.<%= @oracle[:table_name] %>.insert(<%= tuple.to_json %>);
<% end %>

app/views/oracle/dump_script.html.erb
<h1>Oracle#dump_script</h1>
<p>Find me in app/views/oracle/dump_script.html.erb</p>

app/views/oracle/index.html.erb
<h2>Primeiro Exercício</h2>
<p>No primeiro exercício o programa permite transformar tabelas do Oracle em um script para criação de uma coleção em MongoDB</p>
<p>Esse exercício foi dividido em duas partes, uma para transformação de tabelas sem considerar referencias estrangeiras e outra considerando-as</p>
<p>Obs: Não criamos o método para transformação de relações N:N</p>
<%= link_to :acessar, first_ex_path, class: 'btn btn-bg btn-primary' %>

<h2>Segundo Exercício</h2>
<p>No segundo exercício o programa permite a geração de índice para a tabela selecionada</p>
<%= link_to :acessar, index_table_path, class: 'btn btn-bg btn-primary' %>

<h2>Terceiro Exercício</h2>
<p>O terceiro exercício é um script escrito manualmente para realizar as verificações 'CHECK' existentes no Oracle, em forma de validação MongoDB</p>
<%= link_to :acessar, validation_path, class: 'btn btn-bg btn-primary' %>

<h2>Quarto Exercício</h2>
<p>O quarto exercício permite a criação e execução de buscas montadas pelo usuário</p>
<p>O programa retorna o script MongoDB para a realização da busca e também os resultados dela</p>
<%= link_to :acessar, find_wrapper_path, class: 'btn btn-bg btn-primary' %>

<h2>Quinto Exercício</h2>
<p>O quinto exercício permite a inserção ou busca de tuplas no formato:</p>
<pre>{_id: numero, name1: "String de 2000 chars", name2: "String de 2000 chars", ..., name10: "String de 2000 chars}</pre>
<p>São criadas duas collections 'insert_test' e 'insert_test_index' a primeira sem índice e a segunda com índice em 'name1'</p>
<p>São realizadas várias operações e o tempo de execução é retornado</p>

<%= link_to :acessar, benchmark_path, class: 'btn btn-bg btn-primary' %>

<h4>Resultados</h4>
<p>Comparamos os resultados obtidos na Pratica 9 (Oracle) com as operações equivalentes em MongoDB</p>
<p>Resultados das inserções de Oracle contra MongoDB</p>
<table class="table table-bordered">
  <tr>
    <th>Banco</th>
    <th>1.000 tuplas</th> <th>10.000 tuplas</th> <th>100.000 tuplas</th>
  </tr>
  <tr>
    <td>Oracle Com Índice</td>
    <td>64.28s</td> <td>75.62s</td> <td>875.15s</td>
  </tr>
  <tr>
    <td>Oracle Sem Índice</td>
    <td>35.62s</td> <td>282.26s</td> <td>4041.83s</td>
  </tr>
  <tr>
    <td>MongoDB Com Índice</td>
    <td>0.90s</td> <td>8.93s</td> <td>231.20s</td>
  </tr>
  <tr>
    <td>MongoDB Sem Índice</td>
    <td>0.93s</td> <td>8.55s</td> <td>469.76s</td>
  </tr>
</table>
<p>Resultados das buscas de MongoDB</p>
<table class="table table-bordered">
  <tr>
    <th>Banco</th>
    <th>1.000 tuplas</th> <th>10.000 tuplas</th> <th>100.000 tuplas</th>
  </tr>
  <tr>
    <td>MongoDB Com Índice</td>
    <td>0.01s</td> <td>0.16s</td> <td>1.61s</td>
  </tr>
  <tr>
    <td>MongoDB Sem Índice</td>
    <td>0.01s</td> <td>0.13s</td> <td>1.77s</td>
  </tr>
</table>
<p>Obs: Não foi possível comparar as buscar com o Oracle, pois houveram problemas na execução da Prática 9</p>

<p>Pudemos observar que sendo muito mais robusto, o banco de dados Oracle é muito mais lento para operações de inserção. Não pudemos comparar os resultados das buscas por problemas na execução do Oracle, mas os resultados com MongoDB foram bastante satisfatórios, com tempos muito próximos com ou sem índice, o que sugere que o banco crie índices temporários para busca em tabelas de muito acesso</p>

app/views/oracle/mongo_script.html.erb
<%= link_to 'Voltar', @oracle[:back_path], class: 'btn btn-md btn-primary' %>
<%= link_to 'Copiar', '#', class: 'btn btn-md btn-success copy-text', data: {id: 'code'} %>
<br />
<br />
<br />

<pre id="code">
<%= render :partial => 'oracle/partial_mongo_document' %>
</pre>